services:
  db:
    image: mysql:latest
    container_name: mysql
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db_data/mysql:/var/lib/mysql
    ports:
      - "5506:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: emlog
      MYSQL_USER: emlog
      MYSQL_PASSWORD: emlog
    networks:
      - emlog_network

  #  db:
  #    image: mariadb:latest
  #    container_name: mariadb
  #    command:
  #      - --default_authentication_plugin=mysql_native_password
  #      - --character-set-server=utf8mb4
  #      - --collation-server=utf8mb4_unicode_ci
  #      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,ONLY_FULL_GROUP_BY
  #    volumes:
  #      - ./db_data/mariadb:/var/lib/mysql
  #    ports:
  #      - "5506:3306"
  #    restart: always
  #    environment:
  #      MARIADB_ROOT_PASSWORD: 12345678
  #      MARIADB_DATABASE: emlog
  #      MARIADB_USER: emlog
  #      MARIADB_PASSWORD: emlog
  #    networks:
  #      - emlog_network

  php:
    image: emlog/emlog:pro-php8.1
    container_name: php
    volumes:
      - ./:/app/emlog
    working_dir: /app/emlog
    networks:
      - emlog_network
    environment:
      EMLOG_ENV: develop
      EMLOG_DB_HOST: db
      EMLOG_DB_USER: emlog
      EMLOG_DB_NAME: emlog
      EMLOG_DB_PASSWORD: emlog

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./:/app/emlog
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    networks:
      - emlog_network
    depends_on:
      - php

  # redis:
  #   image: redis
  #   networks:
  #     - emlog_network

networks:
  emlog_network:
    external: true