<?php

$lang = array(

//---------------------------
//admin/navbar.php
    'address_generated' => '该导航地址由系统生成，无法修改',//'The address generated by the navigation system, can not be modified',

//---------------------------
//admin/views/navbar.php
    'nav_manage' => '导航管理',//'Navigation management',
    'nav_delete_ok' => '删除导航成功',//'Navigation deleted successfully',
    'nav_edit_ok' => '修改导航成功',//'Navigation modifyied successfully',
    'nav_add_ok' => '添加导航成功',//'Navigation added successfully',
    'nav_name_url_empty' => '导航名称和地址不能为空',//'Navigation name and address can not be empty',
    'nav_no_order' => '没有可排序的导航',//'There is no order of navigation',
    'nav_default_nodelete' => '默认导航不能删除',//'You can not delete the default navigation',
    'select_category' => '请选择要添加的分类',//'Please select the category you want to add',
    'select_page' => '请选择要添加的页面',//'Please select the page you want to add',
    'id' => '序号',//'ID',
    'type' => '类型',//'Type',
    'status' => '状态',//'Status',
    'view' => '查看',//'View',
    'address' => '地址',//'Address',
    'system' => '系统',//'System',
    'page' => '页面',//'Page',
    'custom' => '自定',//'Custom',
    'nav_edit' => '编辑导航',//'Edit navigation',
    'nav_hide_click' => '点击隐藏导航',//'Click to hide navigation',
    'show' => '显示',//'Show',
    'nav_show_click' => '点击显示导航',//'Click to show navigation',
    'hide' => '隐藏',//'Hide',
    'edit' => '编辑',//'Edit',
    'nav_no' => '还没有添加导航',//'Has not yet added navigation',
    'order_change' => '保存拖动排序',//'Change order',
    'nav_add_custom' => '添加自定义导航',//'Add custom navigation',
    'nav_name' => '导航名称',//'Navigation Name',
    'nav_url_http' => '地址(带http)',//'Address (with http)',
    'no' => '无',//'No',
    'nav_parent' => '父导航',//'Parent navigation',
    'open_new_win' => '新窗口打开',//'Open in new window',
    'add' => '添加',//'Add',
    'nav_add_category' => '添加分类到导航',//'Add category navigation',
    'no_categories' => '还没有分类',//'No categories',
    'nav_page_add' => '添加页面到导航',//'Add pages to the navigation',
    'pages_no' => '还没页面',//'No pages',

//---------------------------
//admin/views/naviedit.php
    'nav_modify' => '修改导航',//'Modify navigation',
    'nav_address' => '导航网址',//'Navigation URL',

);
